id: A4403CEB1
title: An Appeal for the Prosperity of Teaching and Studying the Five Major Scriptures
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:10:50.867407
  last_modified_at: 2022-03-01 01:10:50.867415
